export { prisma } from "./client";
export {
  DEFAULT_TENANT_ID,
  DEFAULT_TENANT_SLUG,
  TENANT_SCOPED_MODELS,
  currentTenantId,
  getTenantContext,
  isTenantScopedModel,
  forEachActiveTenant,
  requireTenant,
  runWithTenant,
  runWithTenantAsync,
  scopeWhere,
  tenantCodeKey,
  tenantDayOfWeekKey,
  tenantEmailKey,
  tenantPhoneKey,
  tenantSkuKey,
  tenantSlugKey,
  withTenantCreate,
  type TenantContext,
  type TenantScopedModel,
  type TenantSettings,
} from "./tenant-context";
export type {
  Appointment,
  AppointmentStatus,
  AuditLog,
  BookingVerification,
  BusinessHours,
  CallLog,
  Channel,
  Customer,
  CustomerNote,
  CustomerNoteKind,
  DataRequest,
  DataRequestStatus,
  DataRequestType,
  InventoryMovement,
  InventoryMovementType,
  NotificationLog,
  NotificationStatus,
  Payment,
  PaymentStatus,
  Product,
  RecurringSeries,
  ReviewRequest,
  RoleKey,
  Service,
  StaffProfile,
  Tenant,
  TenantStatus,
  Voucher,
  VoucherRedemption,
  Waitlist,
  WaitlistStatus,
} from "@prisma/client";
export type { Prisma } from "@prisma/client";
