export { prisma } from "./client";
export type {
  Appointment,
  AppointmentStatus,
  AuditLog,
  BookingVerification,
  BusinessHours,
  CallLog,
  Channel,
  Customer,
  CustomerNote,
  CustomerNoteKind,
  DataRequest,
  DataRequestStatus,
  DataRequestType,
  InventoryMovement,
  InventoryMovementType,
  NotificationLog,
  NotificationStatus,
  Payment,
  PaymentStatus,
  Product,
  RecurringSeries,
  ReviewRequest,
  RoleKey,
  Service,
  StaffProfile,
  Voucher,
  VoucherRedemption,
  Waitlist,
  WaitlistStatus,
} from "@prisma/client";
export type { Prisma } from "@prisma/client";
